language: python

python:
  - 2.6
  - 2.7
  - 3.3

env:
  - DJANGO=Django==1.4.15
  - DJANGO=Django==1.5.10
  - DJANGO=Django==1.6.7
  - DJANGO=Django==1.7
  - DJANGO=Django==3.0.3
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install --use-mirrors coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=Django==1.6.7
   - python: 2.6
     env: DJANGO=Django==1.7
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/master
   - python: 3.3
     env: DJANGO=Django==1.4.15

after_success: coveralls
